# Using OP Sepolia Testnet as the reference chain even though it's the eris betanet with overriden addresses on the scr
l2chains = [
    {name = "freya-0", chainId = 420110015},
    {name = "freya-1", chainId = 420110016}
]

fallbackAddressesJsonPath = "src/improvements/tasks/sep/125-opcm-upgrade-v410-freya-u16/addresses.json"
templateName = "OPCMUpgradeV410"

[[opcmUpgrades]]
chainId = 420110015
# Freya prestate, to get:
absolutePrestate = "0x039fb00f964358d326de5804afb4e70a1ca34f9e56c60350b6c8a41fff302490"
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-10"

[[opcmUpgrades]]
chainId = 420110016
# Freya prestate, to get:
absolutePrestate = "0x039fb00f964358d326de5804afb4e70a1ca34f9e56c60350b6c8a41fff302490"
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"

[addresses]
OPCM = "0x3bb6437aba031afbf9cb3538fa064161e2bf2d78" # Freshly deployed on Sepolia
StandardValidatorV410 = "0x7b4d2a02d5fa6c7c98d835d819956ebb876ff439" # Freshly deployed on Sepolia