set positional-arguments

# default recipe to display help information
default:
  @just --list

# Generate the `input.json` with a dispute game address to blacklist
generate-input *args='':
  #!/usr/bin/env bash
  BLACKLIST_GAME_SIG="blacklistDisputeGame(address,address)"
  ENCODED_BLACKLIST_CALL="$(cast calldata $BLACKLIST_GAME_SIG $1 $2)"

  cp ./input-template.json ./input.json
  jq "(.transactions[0].data = \"$ENCODED_BLACKLIST_CALL\") |
          (.transactions[0].contractInputsValues._portal = \"$1\") |
          (.transactions[0].contractInputsValues._game = \"$2\")" ./input.json > ./input.tmp.json
  mv ./input.tmp.json ./input.json 
