templateName = "OPCMUpdatePrestateV410"

[[l2chains]]
chainId = 1301
name = "Unichain Sepolia Testnet"

[[opcmUpgrades]]
chainId = 1301
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc9"  # op-program/v1.6.1 - https://github.com/ethereum-optimism/superchain-registry/blob/47f21fb1291999cb9a46653dd92d7cd55b6e3821/validation/standard/standard-prestates.toml#L6C9-L6C75
# The above prestate needs to be updated with the correct Fusaka Absolute Prestate
expectedValidationErrors = "PROXYA-10,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"

[addresses]
OPCM = "0x3bb6437aba031afbf9cb3538fa064161e2bf2d78" # version 3.2.0 https://github.com/ethereum-optimism/superchain-registry/blob/40526b1288534f6b84b7aae21d13c0b5f5b12f47/validation/standard/standard-versions-sepolia.toml#L23
StandardValidatorV410 = "0x7b4d2a02d5fa6c7c98d835d819956ebb876ff439" # Sepolia https://github.com/ethereum-optimism/optimism/blob/f79ed8b9c9cbdbf8bb492074f3f98da7f072e21a/op-validator/pkg/validations/addresses.go#L30

[stateOverrides]
# Unichain Sepolia ProxyAdminOwner:
0xd363339eE47775888Df411A163c586a8BdEA9dbf = [ # L1PAO
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 38}
]
