set dotenv-load

export rpcUrl := env_var('ETH_RPC_URL')
export optimismPortalAddr := env_var('OPTIMISM_PORTAL_ADDR')
export safeAddr := env_var('SAFE_ADDR')
export location := `pwd`

jsonFile := ''

install: install-presigner

install-presigner:
  #!/usr/bin/env bash
  cd ~
  git clone https://github.com/ethereum-optimism/presigner.git
  cd presigner
  make clean-lib forge-deps
  go build
  go install
  go install tools/onepass/1p.go
  export PATH=$PATH:~/go/bin

simulate jsonFile='':
  #!/usr/bin/env bash
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file {{jsonFile}} \
    simulate

sign hdPath='0' jsonFile='':
  #!/usr/bin/env bash
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file {{jsonFile}} \
    --ledger \
    --hd-paths "m/44'/60'/{{hdPath}}'/0/0" \
    sign

execute hdPath='0':
  #!/usr/bin/env bash
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file {{jsonFile}} \
    --ledger \
    --hd-paths "m/44'/60'/{{hdPath}}'/0/0" \
    execute

get-owners:
  #!/usr/bin/env bash
  cast call -r ${rpcUrl} ${safeAddr} "getOwners()(address[])"

prepare:
  #!/usr/bin/env bash
  echo creating 5 tx...
  echo
  cd ~/presigner
  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 86 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --script-name CallUnpause \
      --json-file tx/draft-unpause-87.json \
      --safe-nonce 87 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 88 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 89 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 90 \
      create

  mv tx/draft-86.json ${location}/tx
  mv tx/draft-unpause-87.json ${location}/tx
  mv tx/draft-88.json ${location}/tx
  mv tx/draft-89.json ${location}/tx
  mv tx/draft-90.json ${location}/tx