l2chains = [
    {name = "freya-0", chainId = 420110013},
    {name = "freya-1", chainId = 420110014}
]

fallbackAddressesJsonPath = "src/improvements/tasks/sep/123-opcm-superchainconfig-v410-freya-u15/addresses.json"
templateName = "OPCMUpgradeSuperchainConfigV410"
allowOverwrite = ["SuperchainConfig", "SuperchainConfigProxyAdmin"]

# OP Sepolia Testnet
[[opcmUpgrades]]
chainId = 420110013
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
expectedValidationErrors = ""

[[opcmUpgrades]]
chainId = 420110014
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
expectedValidationErrors = ""

[addresses]
OPCM = "0x3bb6437aba031afbf9cb3538fa064161e2bf2d78" # Freshly deployed on Sepolia
StandardValidatorV410 = "0x7b4d2a02d5fa6c7c98d835d819956ebb876ff439" # Freshly deployed on Sepolia
SuperchainConfig = "0x1B1ce2a9cEd5A6d4C4b3384D8D8F7EA8031896E2"
SuperchainConfigProxyAdmin = "0x3979c2cb56Aa8E82C4bC17286181F8C660612595"