set positional-arguments

# default recipe to display help information
default:
  @just --list

# Generate the `input.json` with a DelayedWETH address to recover bonds
generate-input delayed_weth:
  #!/usr/bin/env bash
  sum=$(cat meta.json | jq '[.[]] | add')
  AMOUNT=$(cast --to-hex $sum)
  RECOVER_WETH_SIG="recover(uint256)"
  ENCODED_RECOVER_WETH_CALL=$(cast calldata $RECOVER_WETH_SIG $AMOUNT)

  cp ./input-template.json ./input.json
  jq "(.transactions[0].to = \"{{delayed_weth}}\") |
          (.transactions[0].data = \"$ENCODED_RECOVER_WETH_CALL\") |
          (.transactions[0].contractInputsValues._wad = \"$AMOUNT\")" ./input.json > ./input.tmp.json && mv ./input.tmp.json ./input.json
