# RevShare Upgrade and Setup Configuration

templateName = "RevShareUpgradeAndSetup"

# L2 chains to target
l2chains = [
  {name = "Soneium", chainId = 1868}
]

safeAddress = "ProxyAdminOwner"

# RevShareContractsUpgrader address
# https://github.com/ethereum-optimism/superchain-ops/blob/main/src/tasks/eth/037-rev-share-ink-soneium/config.toml#L11
revShareUpgrader = "0x71241bbae674967dD523e621c272Ea32cf33119A"

# RevShare configurations (one per chain) - flattened arrays
portals = [
  # https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/soneium.toml#L49
  "0x88e529A6ccd302c948689Cd5156C83D4614FAE92" # Soneium Mainnet Portal
]

chainFeesRecipients = [
  # https://github.com/ethereum-optimism/superchain-ops/blob/main/src/tasks/eth/037-rev-share-ink-soneium/config.toml#L21
  "0xF07b3169ffF67A8AECdBb18d9761AEeE34591112"
]

# 2 ether
l1WithdrawerMinWithdrawalAmounts = [2000000000000000000]

# FeesDepositor address in mainnet
l1WithdrawerRecipients = [
  # https://github.com/ethereum-optimism/superchain-ops/blob/main/src/tasks/eth/037-rev-share-ink-soneium/config.toml#L30
  "0xed9B99a703BaD32AC96FDdc313c0652e379251Fd"
]
l1WithdrawerGasLimits = [800000]

[addresses]
# https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/soneium.toml#L45
ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"

[stateOverrides]
# ProxyAdminOwner
# https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/soneium.toml#L45
0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 34}
]
# Foundation Upgrades Safe
# https://github.com/ethereum-optimism/superchain-ops/blob/main/src/addresses.toml#L5
0x847B5c174615B1B7fDF770882256e2D3E95b9D92 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 54}
]
# Security Council
# https://github.com/ethereum-optimism/superchain-ops/blob/main/src/addresses.toml#L6
0xc2819DC788505Aac350142A7A707BF9D03E3Bd03 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 56}
]
