set dotenv-load

simulate hdPath='0':
  #!/usr/bin/env bash
  here=$(pwd)
  cd ../..
  echo "getting signer address..."
  signer=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  echo "Simulating with: ${signer}"
  echo ""
  export OWNER_SAFE=${COUNCIL_SAFE}
  forge script SignFromJson --via-ir --rpc-url ${ETH_RPC_URL} \
    --sig "signJson(string)" "${here}/input.json" \
    --sender ${signer}

sign hdPath='0':
  #!/usr/bin/env bash
  here=$(pwd)
  cd ../..
  echo "getting signer address..."
  signer=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  echo "Signing with: ${signer}"
  echo ""
  export OWNER_SAFE=${COUNCIL_SAFE}
  $(go env GOPATH)/bin/eip712sign --ledger --hd-paths "m/44'/60'/{{hdPath}}'/0/0" -- \
    forge script SignFromJson --via-ir --rpc-url ${ETH_RPC_URL} \
    --sig "signJson(string)" "${here}/input.json"

execute hdPath='0':
  #!/usr/bin/env bash
  here=$(pwd)
  cd ../..
  sender=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  export OWNER_SAFE=${COUNCIL_SAFE}
  forge script --fork-url ${ETH_RPC_URL} SignFromJson \
  --sig "runJson(string,bytes)" ${here}/input.json ${SIGNATURES} \
  --ledger --hd-paths "m/44'/60'/{{hdPath}}'/0/0" --broadcast \
  --sender ${sender}

prepare hdPath='0':
  #!/usr/bin/env bash
  here=$(pwd)
  cd ../..
  sender=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  forge script DeployHelloWorld --rpc-url ${ETH_RPC_URL} \
    --ledger --hd-paths "m/44'/60'/{{hdPath}}'/0/0" --broadcast \
    --sig 'run(address)' $COUNCIL_SAFE \
    --sender ${sender}
