set dotenv-load

export councilSafe := env_var('COUNCIL_SAFE')
export ownerSafe := env_var('OWNER_SAFE')
export rpcUrl := env_var_or_default('ETH_RPC_URL', "https://ethereum.publicnode.com")

deploy-contracts hdPath='0':
  #!/usr/bin/env bash
  sender=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  forge build
  forge script DeployNestedRehearsal.sol --ffi \
    --fork-url ${rpcUrl} \
    --ledger --hd-paths "m/44'/60'/{{hdPath}}'/0/0" \
    --broadcast \
    --sender ${sender}
