templateName = "DisableModule"

safeAddressString = "FoundationOperationsSafe"
moduleToDisable = "0xc6f7C07047ba37116A3FdC444Afb5018f6Df5758"

# This is the module in the list of modules returned by calling the getModulesPaginated function
# on the Safe contract. If there is only one module in the list, then this can be set to the
# SENTINEL_MODULE address (0x1).
previousModule = "0x0000000000000000000000000000000000000001"