set dotenv-load

new-rehearsal:
  # todo take keystore as an argument
  # the items below are missing:
  # --keystore
  # --sender
  # --broadcast

deploy-safe:
  forge script DeploySafe \
    --sig 'run(address[],uint256,string,string)' \
    $ADDRESSES $THRESHOLD $NAME $(pwd)/safes

deploy-helloworld:
  forge script DeployHelloWorld \
    --sig 'run(address)' $SAFE_ADDRESS