set dotenv-load

export rpcUrl := env_var_or_default('ETH_RPC_URL', "https://ethereum.publicnode.com")
export signatures := env_var_or_default('SIGNATURES', '')
export bundle := "input"
export location := `pwd`
export randomPersonEoa := "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"

simulate-council hdPath='0':
  #!/usr/bin/env bash
  echo "running simulation..."
  forge script NestedSignFromJson \
    --rpc-url ${rpcUrl} \
    --sender "0xD52FCd0F86bAb7bFA70F0A33f9c90D3afE87d675" \
    --sig "signJson(string,address)" \
    "${location}/${bundle}.json" \
    "$COUNCIL_SAFE"

sign-council hdPath='0':
  #!/usr/bin/env bash
  echo "getting signer address..."
  signer=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  echo "Signing with: ${signer}"
  echo ""
  $(go env GOPATH)/bin/eip712sign --ledger --hd-paths "m/44'/60'/{{hdPath}}'/0/0" -- \
  forge script NestSignFromJson \
    --rpc-url ${rpcUrl} \
    --sig "signJson(string,address)" \
    "${location}/${bundle}.json" \
    "$COUNCIL_SAFE"

simulated-approve-council hdPath='0':
  #!/usr/bin/env bash
  forge script NestedSignFromJson \
    --fork-url ${rpcUrl} \
    --sender ${randomPersonEoa} \
    --sig "approveJson(string,address,bytes)" \
    ${location}/${bundle}.json \
    "$COUNCIL_SAFE" \
    ${signatures}

simulated-run hdPath='0':
  #!/usr/bin/env bash
  forge script NestedSignFromJson \
    --fork-url ${rpcUrl} \
    --sender ${randomPersonEoa} \
    --sig "runJson(string)" \
    ${location}/${bundle}.json
