export rpcUrl := env_var_or_default('ETH_RPC_URL', "https://ethereum.publicnode.com")

sign hdPath='0':
  #!/usr/bin/env bash
  here=$(pwd)
  cd ../..
  echo "getting signer address..."
  signer=$(cast wallet address --ledger --mnemonic-derivation-path "m/44'/60'/{{hdPath}}'/0/0")
  echo "Signing with: ${signer}"
  echo ""
  $(go env GOPATH)/bin/eip712sign --ledger --hd-paths "m/44'/60'/{{hdPath}}'/0/0" -- \
  forge script SignFromJson --via-ir --rpc-url ${rpcUrl} --sig "signJson(string)" "${here}/hello-world.json"

execute:
	forge script --rpc-url ${rpcUrl} SignFromJson \
	--sig "run()" --ledger --hd-paths "m/44'/60'/$(LEDGER_ACCOUNT)'/0/0" --sender $(SENDER) --broadcast "${here}/hello-world.json"
