l2chains = [    
    {name = "OP Mainnet", chainId = 10},
    {name = "Ink", chainId = 57073}
]

templateName = "OPCMUpgradeV400"

# OP Mainnet
[[opcmUpgrades]]
chainId = 10
# prestates."1.6.1-rc.1
# https://github.com/ethereum-optimism/superchain-registry/blob/d82a61168fd1d7ef522ed8e213ce23c853031495/validation/standard/standard-prestates.toml#L6
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
expectedValidationErrors = ""

# Ink
[[opcmUpgrades]]
chainId = 57073
# prestates."1.6.1-rc.1
# https://github.com/ethereum-optimism/superchain-registry/blob/d82a61168fd1d7ef522ed8e213ce23c853031495/validation/standard/standard-prestates.toml#L6
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
expectedValidationErrors = ""

[addresses]
# https://github.com/ethereum-optimism/superchain-registry/blob/a0e62ab68db1d6e0f0fc2e449747146f3d9b312e/validation/standard/standard-versions-mainnet.toml#L22
OPCM = "0x4fefd0c327d08143be8037c45f8a29fa0d711e50"
StandardValidatorV400 = "0x3dfc5e44043DC5998928E0b8280136b7352d3F70"