set dotenv-load

export rpcUrl := env_var('ETH_RPC_URL')
export optimismPortalAddr := env_var('OPTIMISM_PORTAL_ADDR')
export safeAddr := env_var('SAFE_ADDR')
export location := `pwd`

jsonFile := ''

install: install-presigner

install-presigner:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  cd $REPO_ROOT
  mkdir -p bin || true
  PATH="$REPO_ROOT/bin:$PATH"
  cd lib/presigner
  make clean-lib forge-deps
  go build
  cp presigner $REPO_ROOT/bin
  go build tools/onepass/1p.go
  cp 1p $REPO_ROOT/bin
  cd $REPO_ROOT
  cd lib/eip712sign
  go build
  cp eip712sign $REPO_ROOT/bin

whoami hdPath='0':
    #!/usr/bin/env bash
    REPO_ROOT=`git rev-parse --show-toplevel`
    $REPO_ROOT/bin/eip712sign --address --hd-paths "m/44'/60'/{{hdPath}}'/0/0" --ledger

simulate jsonFile='':
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    simulate

sign hdPath='0' jsonFile='':
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    --ledger \
    --hd-paths "m/44'/60'/{{hdPath}}'/0/0" \
    sign

execute hdPath='0':
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    --ledger \
    --hd-paths "m/44'/60'/{{hdPath}}'/0/0" \
    execute

get-owners:
  #!/usr/bin/env bash
  cast call -r ${rpcUrl} ${safeAddr} "getOwners()(address[])"

prepare:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  cd $REPO_ROOT/lib/presigner
  echo creating 5 tx...
  echo
  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 86 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --script-name CallUnpause \
      --json-file tx/draft-unpause-87.json \
      --safe-nonce 87 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 88 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 89 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${optimismPortalAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 90 \
      create

  mv tx/draft-86.json ${location}/tx
  mv tx/draft-unpause-87.json ${location}/tx
  mv tx/draft-88.json ${location}/tx
  mv tx/draft-89.json ${location}/tx
  mv tx/draft-90.json ${location}/tx