# Freya Devnet on u15
l2chains = [
    {name = "freya-u15-0", chainId = 420110013},
    {name = "freya-u15-1", chainId = 420110014}
]

fallbackAddressesJsonPath = "src/tasks/sep/025-opcm-upgrade-v410-freya-bn-u15/addresses.json"
templateName = "OPCMUpgradeV410"

[[opcmUpgrades]]
chainId = 420110013
# Freya prestate:
absolutePrestate = "0x03f0fcd170d6538082f38fd2911a7169162f1f0922253325851a5b0b97b920d8" # Source: https://github.com/ethereum-optimism/devnets/blob/ea0a8e288486ea0059b32d779bb648899abc984c/betanets/freya-u15/op-program/prestates.json#L3

# PROXYA-10: The PAO is not the standard one
# SYSCON-140: The SYSCON is not the standard one
# DF-30: The DF is not the standard one
# PDDG-DWETH-30: The PDDG is not the standard one
# PDDG-130: The PDDG is not the standard one
# PLDG-10: The PLDG is not the standard one
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-10" # Source: https://github.com/ethereum-optimism/devnets/blob/ea0a8e288486ea0059b32d779bb648899abc984c/betanets/freya-u15/op-program/prestates.json#L3

[[opcmUpgrades]]
chainId = 420110014
# Freya prestate:
absolutePrestate = "0x03f0fcd170d6538082f38fd2911a7169162f1f0922253325851a5b0b97b920d8"

# PROXYA-10: The PAO is not the standard one
# SYSCON-140: The SYSCON is not the standard one
# DF-30: The DF is not the standard one
# PDDG-DWETH-30: The PDDG is not the standard one
# PDDG-130: The PDDG is not the standard one
# PLDG-DWETH-30: The PLDG is not the standard one
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"

[addresses]
OPCM = "0x3bb6437aba031afbf9cb3538fa064161e2bf2d78" # Source: https://www.notion.so/oplabs/Freya-bootstrap-addresses-26bf153ee1628028a12ae035916a904c?source=copy_link
StandardValidatorV410 = "0x7b4d2a02d5fa6c7c98d835d819956ebb876ff439" # Source: https://www.notion.so/oplabs/Freya-bootstrap-addresses-26bf153ee1628028a12ae035916a904c?source=copy_link

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 37}
]