set dotenv-load

setup rehearsal suffix="rehearsal":
  #!/usr/bin/env bash
  set -euxo pipefail
  prefix=$(date +'%Y-%m-%d')
  rehearsal={{rehearsal}}
  suffix={{suffix}}
  template_folder="templates/${rehearsal}"
  destination_folder="${prefix}-${rehearsal}-${suffix}"
  rm -rf "${template_folder}/{cache,lib,out}"
  cp -r "${template_folder}" "${destination_folder}"
  git add "${destination_folder}"
