l2chains = [{name = "OP Sepolia Testnet", chainId = 11155420}]

templateName = "OPCMUpgradeV200"

[opcmUpgrades]
absolutePrestates = [{absolutePrestate = "0x035ac388b5cb22acf52a2063cfde108d09b1888655d21f02f595f9c3ea6cbdcd", chainId = 11155420}]
