# this is the file used to determine the network configuration

safeNonce = 67
isNestedSafe = false
l2chains = [{name = "Orderly", chainId = 291}, {name = "Metal", chainId = 1750}]

[gasConfigs]
gasLimits = [{chainId = 291, gasLimit = 100000000}, {chainId = 1750, gasLimit = 100000000}]
gasScalars = [{chainId = 291, overhead = 1000000000, scalar = 1}, {chainId = 1750, overhead = 1000000000, scalar = 1}]
