# Superchain Sepolia Testnets
l2chains = [
    {name = "Unichain Sepolia Testnet", chainId = 1301}
]

templateName = "OPCMUpgradeV410"

# The absolute prestate does come from https://www.notion.so/oplabs/U16a-25bf153ee16280aa9050e03ddb4bbaf5

# Unichain Sepolia Testnet
[[opcmUpgrades]]
chainId = 1301
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"

# PROXYA-10: ProxyAdmin owner is not set to L1 PAO multisig - expected
# DF-30: DF-30: DisputeGameFactory owner is not set to L1 PAO multisig - expected
# PDDG-DWETH-30: Permissioned dispute game delayed WETH owner mismatch - expected
# PDDG-130: The challenger is not the standard one - expected
# PLDG-DWETH-30: Permissionless dispute game delayed WETH owner mismatch - expected
expectedValidationErrors = "PROXYA-10,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"


[addresses]
OPCM = "0x3bb6437aba031afbf9cb3538fa064161e2bf2d78" # Freshly deployed on Sepolia
StandardValidatorV410 = "0x7b4d2a02d5fa6c7c98d835d819956ebb876ff439" # Freshly deployed on Sepolia

[stateOverrides]

# L1PAO Unichain Sepolia (Sep-UL1PAO)
0xd363339eE47775888Df411A163c586a8BdEA9dbf = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 37}
]