# this is the file used to determine the network configuration
templateName = "EnableDeputyPauseModuleTemplate"

newModule = "0x76fc2f971fb355d0453cf9f64d3f9e4f640e1754"
safeAddressString = "GuardianSafe"
foundationSafeString = "FoundationUpgradeSafe"
deputyPauseModuleVersion = "2.1.0"