set positional-arguments

# default recipe to display help information
default:
  @just --list

# Generate the `input.json` with the given optimism portal address
generate-input *args='':
  #!/usr/bin/env bash
  CANNON="0"
  SET_GAME_TYPE_SIG="setRespectedGameType(address,uint32)"
  ENCODED_CALL=$(cast calldata $SET_GAME_TYPE_SIG $1 $CANNON)

  cp ./input-template.json ./input.json
  jq "(.transactions[0].data = \"$ENCODED_CALL\") |
          (.transactions[0].contractInputsValues._portal = \"$1\")" ./input.json > ./input.tmp.json
  mv ./input.tmp.json ./input.json 
