set positional-arguments

# default recipe to display help information
default:
  @just --list

# Generate the `input.json` with the given optimism portal address
generate-input OptimismPortalProxyAddress='':
  #!/usr/bin/env bash
  PERMISSIONED_CANNON="1"
  SET_GAME_TYPE_SIG="setRespectedGameType(address,uint32)"
  ENCODED_CALL=$(cast calldata $SET_GAME_TYPE_SIG {{OptimismPortalProxyAddress}} $PERMISSIONED_CANNON)

  cp ./input-template.json ./input.json
  jq "(.transactions[0].data = \"$ENCODED_CALL\") |
          (.transactions[0].contractInputsValues._portal = \"{{OptimismPortalProxyAddress}}\")" ./input.json > ./input.tmp.json
  mv ./input.tmp.json ./input.json 
