l2chains = [    
    {name = "OP Sepolia Testnet", chainId = 11155420}, 
    {name = "Soneium Testnet Minato", chainId = 1946},
    {name = "Ink Sepolia", chainId = 763373}
]

templateName = "OPCMUpgradeV300"

[opcmUpgrades]
absolutePrestates = [
    {absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405", chainId = 11155420},  
    {absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405", chainId = 1946}, 
    {absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405", chainId = 763373}
] # Absolute prestates pulled from https://github.com/ethereum-optimism/superchain-registry/blob/fb900358ab5016de86f37a23265bd94ce927c9c0/validation/standard/standard-prestates.toml#L18

[addresses]
OPCM = "0xfbceed4de885645fbded164910e10f52febfab35" # https://github.com/ethereum-optimism/superchain-registry/blob/f86350dcf5f8c9e439fac0c0eb2d1bd3078b28b8/validation/standard/standard-versions-sepolia.toml#L22
StandardValidatorV300 = "0x19f205b33f5637bfa584074ed040bc43eadc8586" # https://github.com/ethereum-optimism/optimism/blob/develop/op-validator/pkg/validations/addresses.go#L30 
FoundationUpgradeSafe = "0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B" # Owner on the proxy admin owner
SecurityCouncil = "0xf64bc17485f0B4Ea5F06A96514182FC4cB561977" # Owner on the proxy admin owner
