[status]
draft = 0
ready = 1
contingency = 2
signed = 3
executed = 4
cancelled = 5

[[tasks]]
name = "task-00"
status = 1
path = "src/fps/example/task-00"
contractName = "GasConfigTemplate.sol:GasConfigTemplate"

[[tasks]]
name = "task-01"
status = 1
path = "src/fps/example/task-01"
contractName = "DisputeGameUpgradeTemplate.sol:DisputeGameUpgradeTemplate"

[[tasks]]
name = "task-02"
status = 1
path = "src/fps/example/task-02"
contractName = "SetGameTypeTemplate.sol:SetGameTypeTemplate"

[[tasks]]
name = "task-03"
status = 1
path = "src/fps/example/task-03"
contractName = "GasConfigTemplate.sol:GasConfigTemplate"