# Freya Devnet on u16
l2chains = [
    {name = "freya-u16-0", chainId = 420110015},
    {name = "freya-u16-1", chainId = 420110016}
]

fallbackAddressesJsonPath = "src/improvements/tasks/sep/026-opcm-upgrade-v410-freya-bn-u16/addresses.json"
templateName = "OPCMUpgradeV410"

[[opcmUpgrades]]
chainId = 420110015
# Freya prestate:
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"

# PROXYA-10: The PAO is not the standard one
# SYSCON-140: The SYSCON is not the standard one
# DF-30: The DF is not the standard one
# PDDG-DWETH-30: The PDDG is not the standard one
# PDDG-130: The PDDG is not the standard one
# PLDG-10: The PLDG is not the standard one
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-10"

[[opcmUpgrades]]
chainId = 420110016
# Freya prestate:
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"

# PROXYA-10: The PAO is not the standard one
# SYSCON-140: The SYSCON is not the standard one
# DF-30: The DF is not the standard one
# PDDG-DWETH-30: The PDDG is not the standard one
# PDDG-130: The PDDG is not the standard one
# PLDG-DWETH-30: The PLDG is not the standard one
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"

[addresses]
OPCM = "0x3bb6437aba031afbf9cb3538fa064161e2bf2d78" # Freshly deployed on Sepolia
StandardValidatorV410 = "0x7b4d2a02d5fa6c7c98d835d819956ebb876ff439" # Freshly deployed on Sepolia