set dotenv-load

export rpcUrl := env_var('ETH_RPC_URL')
export superchainConfigAddr := env_var('SUPERCHAIN_CONFIG_ADDR')
export safeAddr := env_var('SAFE_ADDR')
export location := `pwd`

jsonFile := ''

install: install-presigner

install-presigner:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  cd $REPO_ROOT
  mkdir -p bin || true
  PATH="$REPO_ROOT/bin:$PATH"
  cd lib/presigner
  # DO NOT MERGE WIHTOUT REMOVING THIS LINE:
  git checkout k0522-pre-signed-pause
  make clean-lib forge-deps
  go build
  cp presigner $REPO_ROOT/bin
  go build tools/onepass/1p.go
  cp 1p $REPO_ROOT/bin
  cd $REPO_ROOT
  cd lib/eip712sign
  go build
  cp eip712sign $REPO_ROOT/bin

whoami hdPath='0':
    #!/usr/bin/env bash
    REPO_ROOT=`git rev-parse --show-toplevel`
    PATH="$REPO_ROOT/bin:$PATH"
    $REPO_ROOT/bin/eip712sign --address --hd-paths "m/44'/60'/{{hdPath}}'/0/0" --ledger

merge jsonFile +signedFiles:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  PATH="$REPO_ROOT/bin:$PATH"
  JSON_FILE=`realpath {{jsonFile}}`
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    merge {{signedFiles}}

verify jsonFile:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  PATH="$REPO_ROOT/bin:$PATH"
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    verify

simulate jsonFile:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  PATH="$REPO_ROOT/bin:$PATH"
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    simulate

sign hdPath jsonFile:
  #!/usr/bin/env bash
  set -x
  REPO_ROOT=`git rev-parse --show-toplevel`
  PATH="$REPO_ROOT/bin:$PATH"
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  if [ -z "$SIMULATE_WITHOUT_LEDGER" ]; then
    SIGNER_FLAGS="--ledger --hd-paths \"m/44'/60'/{{hdPath}}'/0/0\"'"
  else
    SIGNER_FLAGS="--mnemonic \"test test test test test test test test test test test junk\" --sender 0xE7dEA1306D9F829bA469d1904c50903b46ebd02e"
  fi
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    ${SIGNER_FLAGS} \
    sign

execute hdPath jsonFile:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  PATH="$REPO_ROOT/bin:$PATH"
  JSON_FILE=`realpath {{jsonFile}}`
  cd $REPO_ROOT/lib/presigner
  presigner \
    --rpc-url ${rpcUrl} \
    --json-file $JSON_FILE \
    --ledger \
    --hd-paths "m/44'/60'/{{hdPath}}'/0/0" \
    execute

get-owners:
  #!/usr/bin/env bash
  cast call -r ${rpcUrl} ${safeAddr} "getOwners()(address[])"

prepare:
  #!/usr/bin/env bash
  REPO_ROOT=`git rev-parse --show-toplevel`
  PATH="$REPO_ROOT/bin:$PATH"
  cd $REPO_ROOT/lib/presigner
  echo creating 5 tx...
  echo
  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${superchainConfigAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 92 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${superchainConfigAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 93 \
      create

  presigner \
      --chain 1 \
      --rpc-url ${rpcUrl} \
      --target-addr ${superchainConfigAddr} \
      --safe-addr ${safeAddr} \
      --safe-nonce 94 \
      create

  mv tx/draft-92.json ${location}/tx
  mv tx/draft-93.json ${location}/tx
  mv tx/draft-94.json ${location}/tx
